const ABU_COURSES = [
  'Computer Science',
  'Software Engineering',
  'Information Technology',
  'Cyber Security',
  'Electrical Engineering',
  'Electronics Engineering',
  'Mechanical Engineering',
  'Civil Engineering',
  'Architecture',
  'Building',
  'Quantity Surveying',
  'Estate Management',
  'Urban and Regional Planning',
  'Medicine and Surgery',
  'Dentistry',
  'Pharmacy',
  'Nursing Science',
  'Medical Laboratory Science',
  'Biochemistry',
  'Microbiology',
  'Biology',
  'Chemistry',
  'Physics',
  'Mathematics',
  'Statistics',
  'Economics',
  'Accounting',
  'Business Administration',
  'Public Administration',
  'Political Science',
  'Sociology',
  'Mass Communication',
  'English Language',
  'History',
  'Arabic Studies',
  'Islamic Studies',
  'Law',
  'Education',
  'Library and Information Science',
  'Geography',
  'Agriculture',
  'Veterinary Medicine',
];

export default ABU_COURSES;
